/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE24 (coord M4), J2[13]/ADC0_SE17
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0_SE17_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0_SE17_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0_SE17_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTE25 (coord K5), J2[15]/ADC0_SE18
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC0_SE18_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC0_SE18_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC0_SE18_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTC15 (coord B6), J199[4]/K66F_UART4_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_K66F_UART4_TX_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_K66F_UART4_TX_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_K66F_UART4_TX_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTE11 (coord G4), J1[3]/J38[3]/I2S_TX_WCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2S_TX_WCLK_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2S_TX_WCLK_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2S_TX_WCLK_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC1 (coord B11), USONIC_ECHO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_I2S_TXD_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_I2S_TXD_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2S_TXD_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2S_TXD_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2S_TXD_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA6 (coord J7), USONIC_TRIG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CLKOUT_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CLKOUT_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CLKOUT_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CLKOUT_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CLKOUT_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE12 (coord G3), SWITCH
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_I2S_TX_BCLK_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_I2S_TX_BCLK_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2S_TX_BCLK_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2S_TX_BCLK_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2S_TX_BCLK_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC14 (coord C6), J199[3]/K66F_UART4_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_K66F_UART4_RX_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_K66F_UART4_RX_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_K66F_UART4_RX_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB4 (coord G10), J4[8]/ADC1_SE10
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC1_SE10_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC1_SE10_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC1_SE10_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
