/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MK66FN2M0xxx18
package_id: MK66FN2M0VMD18
mcu_data: ksdk2_0
processor_version: 15.0.1
board: FRDM-K66F
external_user_signals: {}
pin_labels:
- {pin_num: G3, pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, label: SWITCH, identifier: I2S_TX_BCLK}
- {pin_num: J7, pin_signal: PTA6/FTM0_CH3/CLKOUT/TRACE_CLKOUT, label: USONIC_TRIG, identifier: CLKOUT}
- {pin_num: B11, pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/SDRAM_A21/I2S0_TXD0, label: USONIC_ECHO, identifier: I2S_TXD}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: M4, peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE17/PTE24/CAN1_TX/UART4_TX/I2C0_SCL/EWM_OUT_b, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: K5, peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE18/PTE25/LLWU_P21/CAN1_RX/UART4_RX/I2C0_SDA/EWM_IN, open_drain: enable, pull_select: up, pull_enable: enable}
  - {pin_num: A3, peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/SDRAM_A9/EWM_OUT_b/SPI1_SCK}
  - {pin_num: B6, peripheral: UART4, signal: TX, pin_signal: PTC15/UART4_TX/FB_AD24/SDRAM_D24, open_drain: disable, pull_select: down, pull_enable: disable}
  - {pin_num: G4, peripheral: FTM3, signal: 'CH, 6', pin_signal: PTE11/I2C3_SCL/I2S0_TX_FS/LPUART0_RTS_b/FTM3_CH6}
  - {pin_num: B11, peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/SPI0_PCS3/UART1_RTS_b/FTM0_CH0/FB_AD13/SDRAM_A21/I2S0_TXD0,
    direction: INPUT, open_drain: disable, pull_enable: disable}
  - {pin_num: J7, peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM0_CH3/CLKOUT/TRACE_CLKOUT, direction: OUTPUT, pull_select: down, pull_enable: enable}
  - {pin_num: G3, peripheral: GPIOE, signal: 'GPIO, 12', pin_signal: PTE12/I2S0_TX_BCLK/FTM3_CH7, direction: INPUT, pull_select: down, pull_enable: enable}
  - {pin_num: C6, peripheral: UART4, signal: RX, pin_signal: PTC14/UART4_RX/FB_AD25/SDRAM_D25}
  - {pin_num: G10, peripheral: ADC1, signal: 'SE, 10', pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/SDRAM_CS1_b/FTM1_FLT0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t CLKOUT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin J7)  */
    GPIO_PinInit(BOARD_INITPINS_CLKOUT_GPIO, BOARD_INITPINS_CLKOUT_PIN, &CLKOUT_config);

    gpio_pin_config_t I2S_TXD_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin B11)  */
    GPIO_PinInit(BOARD_INITPINS_I2S_TXD_GPIO, BOARD_INITPINS_I2S_TXD_PIN, &I2S_TXD_config);

    gpio_pin_config_t I2S_TX_BCLK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE12 (pin G3)  */
    GPIO_PinInit(BOARD_INITPINS_I2S_TX_BCLK_GPIO, BOARD_INITPINS_I2S_TX_BCLK_PIN, &I2S_TX_BCLK_config);

    /* PORTA6 (pin J7) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_CLKOUT_PORT, BOARD_INITPINS_CLKOUT_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[6] = ((PORTA->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | (uint32_t)(kPORT_PullDown));

    /* PORTB4 (pin G10) is configured as ADC1_SE10 */
    PORT_SetPinMux(BOARD_INITPINS_ADC1_SE10_PORT, BOARD_INITPINS_ADC1_SE10_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTC1 (pin B11) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_I2S_TXD_PORT, BOARD_INITPINS_I2S_TXD_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[1] = ((PORTC->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable)

                     /* Open Drain Enable: Open drain output is disabled on the corresponding pin. */
                     | PORT_PCR_ODE(kPORT_OpenDrainDisable));

    /* PORTC14 (pin C6) is configured as UART4_RX */
    PORT_SetPinMux(BOARD_INITPINS_K66F_UART4_RX_PORT, BOARD_INITPINS_K66F_UART4_RX_PIN, kPORT_MuxAlt3);

    /* PORTC15 (pin B6) is configured as UART4_TX */
    PORT_SetPinMux(BOARD_INITPINS_K66F_UART4_TX_PORT, BOARD_INITPINS_K66F_UART4_TX_PIN, kPORT_MuxAlt3);

    PORTC->PCR[15] = ((PORTC->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | PORT_PCR_PS(1U) // enable

                      /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding
                       * pin. */
                      | PORT_PCR_PE(kPORT_PullDisable)

                      /* Open Drain Enable: Open drain output is disabled on the corresponding pin. */
                      | PORT_PCR_ODE(kPORT_OpenDrainDisable));

    /* PORTD5 (pin A3) is configured as FTM0_CH5 */
    PORT_SetPinMux(PORTD, 5U, kPORT_MuxAlt4);

    /* PORTE11 (pin G4) is configured as FTM3_CH6 */
    PORT_SetPinMux(BOARD_INITPINS_I2S_TX_WCLK_PORT, BOARD_INITPINS_I2S_TX_WCLK_PIN, kPORT_MuxAlt6);

    /* PORTE12 (pin G3) is configured as PTE12 */
    PORT_SetPinMux(BOARD_INITPINS_I2S_TX_BCLK_PORT, BOARD_INITPINS_I2S_TX_BCLK_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[12] = ((PORTE->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullDown));

    /* PORTE24 (pin M4) is configured as I2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_ADC0_SE17_PORT, BOARD_INITPINS_ADC0_SE17_PIN, kPORT_MuxAlt5);

    PORTE->PCR[24] = ((PORTE->PCR[24] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    /* PORTE25 (pin K5) is configured as I2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_ADC0_SE18_PORT, BOARD_INITPINS_ADC0_SE18_PIN, kPORT_MuxAlt5);

    PORTE->PCR[25] = ((PORTE->PCR[25] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_ISF_MASK)))

                      /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                       * corresponding PE field is set. */
                      | (uint32_t)(kPORT_PullUp)

                      /* Open Drain Enable: Open drain output is enabled on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_ODE(kPORT_OpenDrainEnable));

    // Hall
    /* PORTC3 (pin B10) is configured as FTM0_CH2 for Hall Sensor input capture */
    PORT_SetPinMux(PORTC, 3U, kPORT_MuxAlt4);

    /* Configure with pull-up for open-drain hall sensors */
    PORTC->PCR[3] = ((PORTC->PCR[3] &
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled */
                     | PORT_PCR_PS(kPORT_PullUp)

                     /* Pull Enable: Internal pull resistor is enabled */
                     | PORT_PCR_PE(1U));

}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
