#include "control_algorithms.h"

#include "fsl_debug_console.h"
#include "hall_sensor.h"
#include "utils.h"

// PID
uint16_t MapControlToDutyCycle(float control)
{
    float pwm_value = PWM_MIN + (control + 1.0f) * (PWM_MAX - PWM_MIN) / 2.0f;
    if (pwm_value < PWM_MIN)
        pwm_value = PWM_MIN;
    if (pwm_value > PWM_MAX)
        pwm_value = PWM_MAX;
    return (uint16_t)(pwm_value * 100.0f);
}
float CalculateError(float x_center)
{
    return CENTER_X - x_center;
}
float CalculateCombinedError(float x_center1, float x_center2)
{
    float error1 = CalculateError(x_center1);
    float error2 = CalculateError(x_center2);

    // Ponderi: 70% aproape, 30% anticipare
    return 0.7f * error1 + 0.3f * error2;
}

void CalculateLaneCenter2(VectorType v1, VectorType v2, float *x_1, float *x_2, float *y_1,
                          float *y_2)
{
    int v1_jos_x = (v1.m_y0 > v1.m_y1) ? v1.m_x0 : v1.m_x1;
    int v1_jos_y = (v1.m_y0 > v1.m_y1) ? v1.m_y0 : v1.m_y1;
    int v2_jos_x = (v2.m_y0 > v2.m_y1) ? v2.m_x0 : v2.m_x1;
    int v2_jos_y = (v2.m_y0 > v2.m_y1) ? v2.m_y0 : v2.m_y1;

    int v1_sus_x = (v1.m_y0 <= v1.m_y1) ? v1.m_x0 : v1.m_x1;
    int v1_sus_y = (v1.m_y0 <= v1.m_y1) ? v1.m_y0 : v1.m_y1;
    int v2_sus_x = (v2.m_y0 <= v2.m_y1) ? v2.m_x0 : v2.m_x1;
    int v2_sus_y = (v2.m_y0 <= v2.m_y1) ? v2.m_y0 : v2.m_y1;

    *x_1 = ((float)v1_jos_x + (float)v2_jos_x) / 2.0f;
    *y_1 = ((float)v1_jos_y + (float)v2_jos_y) / 2.0f;
    *x_2 = ((float)v1_sus_x + (float)v2_sus_x) / 2.0f;
    *y_2 = ((float)v1_sus_y + (float)v2_sus_y) / 2.0f;
}
void CalculateLaneCenter(VectorType v1, VectorType v2, float *x_center, float *y_center)
{
    // Media coordonatelor x și y dintre v1 și v2
    *x_center = ((float)v1.m_x0 + (float)v1.m_x1 + (float)v2.m_x0 + (float)v2.m_x1) / 4.0f;
    *y_center = ((float)v1.m_y0 + (float)v1.m_y1 + (float)v2.m_y0 + (float)v2.m_y1) / 4.0f;
}

// PID
float PID_Control(PIDController *pid, float error)
{
    pid->integral += error;

    if (pid->integral > pid->max_integral)
        pid->integral = pid->max_integral;
    if (pid->integral < -pid->max_integral)
        pid->integral = -pid->max_integral;

    float derivative    = error - pid->previous_error;
    pid->previous_error = error;

    float control = pid->Kp * error + pid->Ki * pid->integral + pid->Kd * derivative;

    if (control < -1.0f)
        control = -1.0f;
    if (control > 1.0f)
        control = 1.0f;
    return control;
}

MotorCommand_t ProcessVectorsPID(VectorType v1, VectorType v2)
{
    float x_center, y_center;
    CalculateLaneCenter(v1, v2, &x_center, &y_center);
    float error = CalculateError(x_center);

    float control_steer = PID_Control(&pid_steering, error);
    uint16_t steer_duty = MapControlToDutyCycle(control_steer);
    uint16_t speed_duty = CalculateSpeedFromDuty(steer_duty);

    if (simulator)
    {
        float rpm = HallSensor_GetRPM();
        float mps = HallSensor_GetSpeed_kmh() / 3.6f;
        PRINTF("-ERR:");
        print_float(error);
        PRINTF(" CONTROL:");
        print_float(control_steer);
        PRINTF(" STEER:%d SPEED:%d RPM:", steer_duty, speed_duty);
        print_float(rpm);
        PRINTF(" MPS:");
        print_float(mps);
        PRINTF("\r\n");
    }
    else
    {
        float rpm = HallSensor_GetRPM();
        float mps = HallSensor_GetSpeed_kmh() / 3.6f;
        PRINTF("-STEER:%d SPEED:%d RPM:", steer_duty, speed_duty);
        print_float(rpm);
        PRINTF(" MPS:");
        print_float(mps);
        PRINTF("\r\n");
    }

    return (MotorCommand_t){.steer_duty = steer_duty, .speed_duty = speed_duty};
}

uint16_t CalculateSpeedFromDuty(uint16_t duty_cycle)
{
    int deviation = abs((int)duty_cycle - 700);
    float scale   = 1.0f - ((float)deviation / 150.0f);
    if (scale < 0.0f)
        scale = 0.0f;

    float pwm_speed = PWM_MIN_SPEED + scale * (PWM_MAX_SPEED - PWM_MIN_SPEED);

    return (uint16_t)(pwm_speed * 100);
}

uint16_t CalculateSpeedFromControl(float control)
{
    if (control < -1.0f)
        control = -1.0f;
    if (control > 1.0f)
        control = 1.0f;

    float deviation = fabsf(control);
    float scale     = 1.0f - deviation;

    float pwm_speed = PWM_MIN_SPEED + scale * (PWM_MAX_SPEED - PWM_MIN_SPEED);

    return (uint16_t)(pwm_speed * 100);
}

/* =========================================================================
 * LQR steering control
 * =========================================================================
 *
 * K is generated by tools/lqr_tuning.py.
 * Run the script and paste its output here to replace the placeholder.
 *
 * The values below are Bryson-scaled starting estimates for
 *   L=0.20 m, v0=1.5 m/s, dt=0.05 s
 * They MUST be replaced with the actual DARE solution before flight.
 *
 * States: [e_lat (m), theta_e (rad), psi_dot (rad/s)]
 */
/* ---- Gain-scheduled LQR: two operating points blended on |theta_e| -----
 * blend = clamp(|theta_e| / LQR_SCHEDULE_THETA, 0, 1)
 * K_eff = K_STRAIGHT + blend * (K_TURN - K_STRAIGHT)               */
static float LQR_K_STRAIGHT[LQR_NUM_STATES] = {
    0.41000000f, /* k_e_lat   — lateral stiffness on straight          */
    0.28000000f, /* k_theta_e — low: tolerates heading noise           */
    0.18000000f  /* k_psi_dot — light damping on straight              */
};
static float LQR_K_TURN[LQR_NUM_STATES] = {
    0.41000000f, /* k_e_lat   — same lateral stiffness in turn         */
    0.45000000f, /* k_theta_e — tested value; 0.71 was saturating      */
    0.28000000f  /* k_psi_dot — more damping to prevent overshoot      */
};
/* ----------------------------------------------------------------------- */

void LQR_SetStraightGains(float k_e_lat, float k_theta_e, float k_psi_dot)
{
    LQR_K_STRAIGHT[0] = k_e_lat;
    LQR_K_STRAIGHT[1] = k_theta_e;
    LQR_K_STRAIGHT[2] = k_psi_dot;
}
void LQR_GetStraightGains(float *k_e_lat, float *k_theta_e, float *k_psi_dot)
{
    *k_e_lat   = LQR_K_STRAIGHT[0];
    *k_theta_e = LQR_K_STRAIGHT[1];
    *k_psi_dot = LQR_K_STRAIGHT[2];
}
void LQR_SetTurnGains(float k_e_lat, float k_theta_e, float k_psi_dot)
{
    LQR_K_TURN[0] = k_e_lat;
    LQR_K_TURN[1] = k_theta_e;
    LQR_K_TURN[2] = k_psi_dot;
}
void LQR_GetTurnGains(float *k_e_lat, float *k_theta_e, float *k_psi_dot)
{
    *k_e_lat   = LQR_K_TURN[0];
    *k_theta_e = LQR_K_TURN[1];
    *k_psi_dot = LQR_K_TURN[2];
}

float CalculateLaneHeading(VectorType v1, VectorType v2)
{
    float angle_sum = 0.0f;
    int valid_count = 0;

    /* v1 and v2 arrive already normalised (y0 >= y1) from PreprocessVectors.
     * atan2(dx, dy) with dy = y0 - y1 >= 0 gives the signed lane angle:
     *   0          straight
     *   positive   lane leans right  (right curve ahead)
     *   negative   lane leans left   (left curve ahead) */
    if (v1.m_index != 255u)
    {
        float dx = (float)v1.m_x1 - (float)v1.m_x0;
        float dy = (float)v1.m_y0 - (float)v1.m_y1; /* >= 0 after normalise */
        angle_sum += atan2f(dx, dy + 0.01f);
        valid_count++;
    }
    if (v2.m_index != 255u)
    {
        float dx = (float)v2.m_x1 - (float)v2.m_x0;
        float dy = (float)v2.m_y0 - (float)v2.m_y1;
        angle_sum += atan2f(dx, dy + 0.01f);
        valid_count++;
    }

    return (valid_count > 0) ? (angle_sum / (float)valid_count) : 0.0f;
}

void LQRState_Update(LQRState_t *state, VectorType v1, VectorType v2)
{
    float x_center, y_center;
    CalculateLaneCenter(v1, v2, &x_center, &y_center);

    /* Lateral error: positive = car is LEFT of lane centre.
     * Note the sign is opposite to CalculateError(); see header sign convention. */
    state->e_lat = (x_center - CENTER_X) * LQR_PIX2M;

    float theta_new = CalculateLaneHeading(v1, v2);

    if (!state->initialized)
    {
        /* First call: seed prev_theta_e so the finite difference starts at 0,
         * not at (theta_new - 0) which would produce a spurious yaw-rate spike. */
        state->prev_theta_e = theta_new;
        state->psi_dot      = 0.0f;
        state->initialized  = true;
    }
    else
    {
        state->psi_dot = (theta_new - state->prev_theta_e) / LQR_DT;
        /* Clamp to physically reachable yaw rate (v*tan(δ_max)/L ≈ 3.7 rad/s at 1.61 m/s).
         * Spikes beyond this are misclassified/noisy vectors, not real dynamics. */
        if (state->psi_dot > 3.0f)
            state->psi_dot = 3.0f;
        if (state->psi_dot < -3.0f)
            state->psi_dot = -3.0f;
    }

    state->theta_e      = theta_new;
    state->prev_theta_e = theta_new;
}

uint16_t LQR_SteerControl(const LQRState_t *state)
{
    float blend = fabsf(state->theta_e) / LQR_SCHEDULE_THETA;
    if (blend > 1.0f) blend = 1.0f;

    float k0 = LQR_K_STRAIGHT[0] + blend * (LQR_K_TURN[0] - LQR_K_STRAIGHT[0]);
    float k1 = LQR_K_STRAIGHT[1] + blend * (LQR_K_TURN[1] - LQR_K_STRAIGHT[1]);
    float k2 = LQR_K_STRAIGHT[2] + blend * (LQR_K_TURN[2] - LQR_K_STRAIGHT[2]);

    /* u = -K * x */
    float delta = -(k0 * state->e_lat + k1 * state->theta_e + k2 * state->psi_dot);

    delta = -delta;

    /* Clamp to physical servo limit */
    if (delta > LQR_MAX_STEER)
        delta = LQR_MAX_STEER;
    if (delta < -LQR_MAX_STEER)
        delta = -LQR_MAX_STEER;

    /* Map steering angle to normalised control [-1, 1] then to PWM.
     * Positive delta (steer left) → negative normalised control → smaller PWM.
     * This matches the existing convention where smaller PWM steers left. */
    float control = -(delta / LQR_MAX_STEER);

    return MapControlToDutyCycle(control);
}

/* =========================================================================
 * PD speed control
 * ========================================================================= */

uint16_t PD_SpeedControl(PDController_t *pd, float target_rpm, float current_rpm)
{
    float error = target_rpm - current_rpm;

    float derivative = 0.0f;
    if (pd->initialized && current_rpm > 0.0f)
        derivative = (error - pd->prev_error) / LQR_DT;

    /* Freeze state on sensor dropout — avoids false derivative spike on recovery */
    if (current_rpm > 0.0f)
        pd->prev_error = error;
    pd->initialized = true;

    /* Feedforward: base PWM that holds ~PD_TARGET_RPM on a flat surface.
     * PD correction is added on top to compensate for load and battery droop. */
    float output = PWM_MIN_SPEED * 100.0f + pd->Kp * error + pd->Kd * derivative;

    if (output > pd->output_max)
        output = pd->output_max;
    if (output < pd->output_min)
        output = pd->output_min;

    return (uint16_t)output;
}

/* =========================================================================
 * Speed–steering coupling
 * =========================================================================
 *
 * Steering neutral = 700.  Full deflection = ±200 units (500 or 900).
 * At full deflection, speed is reduced to SPEED_STEER_MIN_SCALE of target.
 * Reduction is linear between neutral and full deflection.
 * ========================================================================= */

#define SPEED_STEER_COUPLING 0.5f  /* slope: fraction of speed lost per    */
                                   /* unit of normalised steer deflection  */
#define SPEED_STEER_MIN_SCALE 0.4f /* floor: never go below 40 % of target */

float SpeedSteeringCoupling(float target_rpm, uint16_t steer_duty)
{
    /* Normalise deviation from neutral to [0, 1] */
    float deviation = fabsf((float)steer_duty - 700.0f) / 200.0f;
    if (deviation > 1.0f)
        deviation = 1.0f;

    float scale = 1.0f - SPEED_STEER_COUPLING * deviation;
    if (scale < SPEED_STEER_MIN_SCALE)
        scale = SPEED_STEER_MIN_SCALE;

    return target_rpm * scale;
}
